import { zenginMetin } from '@/lib/lexical'

/** Örnek içerik: siteyi ilk açışta dolu görmek için. Gerçek kişi veya kurumlara ait değildir. */

export const ornekYazilar = [
  {
    baslik: 'Bel fıtığında egzersizin önemi',
    ozet: 'Bel fıtığında doğru egzersiz ağrıyı azaltır, hareket kabiliyetini artırır. Hangi egzersizler güvenli, hangilerinden kaçınmalı?',
    kategori: 'ortopedi',
    yazar: 'Fzt. Deniz Aksoy',
    gunOnce: 2,
    renk: ['#0f766e', '#5eead4'],
    icerik: zenginMetin([
      { p: 'Bel fıtığı tanısı alan birçok kişi hareket etmekten çekinir. Oysa uzun süreli hareketsizlik kasları zayıflatır ve ağrının kronikleşmesine yol açabilir.' },
      { h2: 'Egzersiz neden işe yarar?' },
      { p: 'Karın ve sırt kaslarını güçlendiren egzersizler omurgayı destekleyen doğal bir korse oluşturur. Bu da diskler üzerindeki yükü azaltır.' },
      { ul: ['Derin karın kaslarını aktive eden nefes egzersizleri', 'Köprü (bridge) hareketi', 'Kedi-deve esnetmesi', 'Kontrollü yürüyüş programları'] },
      { h2: 'Nelere dikkat etmeli?' },
      { p: 'Egzersizler ağrıyı artırmamalı. Bacağa yayılan ağrı, uyuşma veya güç kaybı varsa programa başlamadan önce mutlaka bir hekime ve fizyoterapiste danışın.' },
    ]),
  },
  {
    baslik: 'Ofis çalışanları için 5 dakikalık boyun egzersizleri',
    ozet: 'Uzun süre ekrana bakmak boyun ve omuz ağrısının en sık nedenlerinden. Masadan kalkmadan yapabileceğiniz basit hareketler.',
    kategori: 'genel-saglik',
    yazar: 'Fzt. Elif Karaca',
    gunOnce: 6,
    renk: ['#1d4ed8', '#93c5fd'],
    icerik: zenginMetin([
      { p: 'Masa başında geçen uzun saatler boynun öne doğru kaymasına ve omuzların yuvarlaklaşmasına neden olur. Günde birkaç kez yapılan kısa egzersizler bu yükü hafifletir.' },
      { h2: 'Egzersiz rutini' },
      { ol: ['Çene içeri çekme: 10 tekrar', 'Boynu yana eğerek esnetme: her yöne 20 saniye', 'Omuz silkme ve geriye yuvarlama: 10 tekrar', 'Kürek kemiklerini birbirine yaklaştırma: 10 tekrar', 'Göğüs kaslarını kapı aralığında esnetme: 30 saniye'] },
      { p: 'Ekranınızı göz hizasına getirmek ve her 45-60 dakikada bir kısa bir mola vermek de en az egzersizler kadar önemlidir.' },
    ]),
  },
  {
    baslik: 'İnme sonrası rehabilitasyon: ilk 3 ay neden kritik?',
    ozet: 'İnme sonrası beynin kendini yeniden düzenleme kapasitesi ilk aylarda en yüksek düzeydedir. Erken ve yoğun rehabilitasyonun faydaları.',
    kategori: 'norolojik',
    yazar: 'Fzt. Murat Yıldız',
    gunOnce: 11,
    renk: ['#7c3aed', '#c4b5fd'],
    icerik: zenginMetin([
      { p: 'İnme (felç) sonrasında kaybedilen fonksiyonların önemli bir kısmı, doğru rehabilitasyonla geri kazanılabilir. Bu süreçte zamanlama çok önemlidir.' },
      { h2: 'Nöroplastisite nedir?' },
      { p: 'Beynin hasar gören bölgelerin görevlerini başka bölgelere aktarabilme yeteneğine nöroplastisite denir. Bu kapasite inmeden sonraki ilk haftalarda ve aylarda en yüksektir.' },
      { h2: 'Rehabilitasyon programı neleri kapsar?' },
      { ul: ['Denge ve yürüme eğitimi', 'Kol ve el fonksiyonlarına yönelik görev odaklı çalışmalar', 'Kas tonusunun düzenlenmesi', 'Günlük yaşam aktivitelerinde bağımsızlık eğitimi'] },
      { p: 'Program; hekim, fizyoterapist, ergoterapist ve dil-konuşma terapistinden oluşan bir ekiple, kişiye özel olarak planlanmalıdır.' },
    ]),
  },
  {
    baslik: 'Koşucularda diz ağrısı: nedenleri ve korunma yolları',
    ozet: 'Koşucu dizi olarak bilinen patellofemoral ağrı sendromu, amatör koşucularda en sık görülen sakatlıklardan biri.',
    kategori: 'sporcu-sagligi',
    yazar: 'Fzt. Deniz Aksoy',
    gunOnce: 17,
    renk: ['#c2410c', '#fdba74'],
    icerik: zenginMetin([
      { p: 'Diz kapağının önünde veya çevresinde hissedilen ağrı, özellikle merdiven inerken ve uzun süre oturduktan sonra belirginleşir.' },
      { h2: 'Sık görülen nedenler' },
      { ul: ['Antrenman yükünü çok hızlı artırmak', 'Kalça ve uyluk kaslarında zayıflık', 'Uygun olmayan ayakkabı seçimi', 'Yetersiz toparlanma süresi'] },
      { h2: 'Korunma' },
      { p: 'Haftalık koşu mesafesini kademeli artırmak, kalça kaslarını güçlendirmek ve koşu tekniğini değerlendirmek sakatlık riskini belirgin şekilde azaltır.' },
    ]),
  },
  {
    baslik: 'Çocuklarda duruş bozuklukları: ailelerin bilmesi gerekenler',
    ozet: 'Ağır okul çantaları ve uzun ekran süresi çocuklarda duruş bozukluklarını artırıyor. Erken fark etmek için nelere bakmalı?',
    kategori: 'pediatrik',
    yazar: 'Fzt. Elif Karaca',
    gunOnce: 24,
    renk: ['#be185d', '#f9a8d4'],
    icerik: zenginMetin([
      { p: 'Büyüme çağındaki çocuklarda omurga henüz gelişimini tamamlamamıştır. Bu dönemde kazanılan alışkanlıklar yetişkinlikteki duruşu doğrudan etkiler.' },
      { h2: 'Evde yapılabilecek basit gözlem' },
      { ul: ['Omuzlar aynı hizada mı?', 'Öne eğildiğinde sırtın bir tarafı daha yüksek görünüyor mu?', 'Baş sürekli öne doğru mu duruyor?'] },
      { p: 'Bu işaretlerden birini fark ederseniz bir çocuk ortopedisti veya fizyoterapistten değerlendirme isteyin. Erken dönemde başlanan egzersizler oldukça etkilidir.' },
    ]),
  },
  {
    baslik: 'Omuz sıkışma sendromunda doğru bilinen yanlışlar',
    ozet: '"Ağrıyorsa hiç kullanma" yaklaşımı omuz sıkışmasında sorunu büyütebilir. Sık yapılan hatalar ve doğru yaklaşım.',
    kategori: 'ortopedi',
    yazar: 'Fzt. Murat Yıldız',
    gunOnce: 33,
    renk: ['#0369a1', '#7dd3fc'],
    icerik: zenginMetin([
      { p: 'Omuz sıkışma sendromu, kolu kaldırırken omuzda hissedilen ağrı ile kendini gösterir. Tedavide en sık yapılan hata omzu tamamen hareketsiz bırakmaktır.' },
      { h2: 'Yanlış: Tamamen dinlenmek' },
      { p: 'Uzun süreli hareketsizlik eklem sertliğine ve kas kaybına yol açar. Ağrıyı artırmayan hareketler devam etmelidir.' },
      { h2: 'Doğru: Kontrollü güçlendirme' },
      { p: 'Rotator manşet ve kürek kemiği kaslarını hedefleyen, fizyoterapist eşliğinde planlanmış bir program çoğu hastada ameliyata gerek kalmadan iyileşme sağlar.' },
    ]),
  },
] as const

const aciklama = (ozet: string, nitelikler: string[], sunulanlar: string[]) =>
  zenginMetin([
    { p: ozet },
    { h3: 'Aranan nitelikler' },
    { ul: nitelikler },
    { h3: 'Sunulanlar' },
    { ul: sunulanlar },
  ])

/** bitisGun: bugünden itibaren gün sayısı. Negatif değer süresi dolmuş ilan demektir. */
export const ornekIlanlar = [
  {
    baslik: 'Tam zamanlı fizyoterapist',
    kurum: 'Moda Fizik Tedavi Merkezi',
    sehir: 'istanbul',
    ilce: 'Kadıköy',
    calismaSekli: 'tam-zamanli',
    bitisGun: 21,
    iletisim: { eposta: 'ik@ornek-moda-fizik.test', telefon: '0216 000 00 01' },
    aciklama: aciklama(
      'Ortopedi ve spor yaralanmaları alanında çalışacak ekip arkadaşı arıyoruz.',
      ['Fizyoterapi ve rehabilitasyon lisans mezunu', 'En az 2 yıl klinik deneyim', 'Manuel terapi sertifikası tercih sebebi'],
      ['SGK + özel sağlık sigortası', 'Eğitim ve kurs desteği', 'Hafta içi mesai'],
    ),
  },
  {
    baslik: 'Nörolojik rehabilitasyon fizyoterapisti',
    kurum: 'Çankaya Rehabilitasyon Kliniği',
    sehir: 'ankara',
    ilce: 'Çankaya',
    calismaSekli: 'tam-zamanli',
    bitisGun: 12,
    iletisim: { eposta: 'basvuru@ornek-cankaya-rehab.test' },
    aciklama: aciklama(
      'İnme ve omurilik yaralanması hastalarıyla çalışacak deneyimli fizyoterapist arıyoruz.',
      ['Bobath veya PNF eğitimi', 'Nörolojik hastalarla en az 3 yıl deneyim', 'Ekip çalışmasına yatkınlık'],
      ['Rekabetçi maaş', 'Yemek ve servis', 'Yıllık kongre desteği'],
    ),
  },
  {
    baslik: 'Yarı zamanlı fizyoterapist (hafta sonu)',
    kurum: 'Karşıyaka Hareket Stüdyosu',
    sehir: 'izmir',
    ilce: 'Karşıyaka',
    calismaSekli: 'yari-zamanli',
    bitisGun: 5,
    iletisim: { telefon: '0232 000 00 02' },
    aciklama: aciklama(
      'Cumartesi ve pazar günleri klinik pilates ve bireysel seanslar için ekip arkadaşı arıyoruz.',
      ['Klinik pilates sertifikası', 'İletişimi güçlü'],
      ['Seans başı ücret', 'Esnek program'],
    ),
  },
  {
    baslik: 'Sporcu sağlığı fizyoterapisti',
    kurum: 'Nilüfer Spor Kulübü',
    sehir: 'bursa',
    ilce: 'Nilüfer',
    calismaSekli: 'tam-zamanli',
    bitisGun: 28,
    iletisim: { eposta: 'saglik@ornek-nilufer-spor.test', basvuruLinki: 'https://ornek-nilufer-spor.test/kariyer' },
    aciklama: aciklama(
      'Profesyonel basketbol takımımızın sağlık ekibine katılacak fizyoterapist arıyoruz.',
      ['Sporcu sağlığı alanında deneyim', 'Kinesyo bantlama ve sahada ilk yardım bilgisi', 'Deplasmanlara katılabilecek'],
      ['Kulüp imkânları', 'Prim sistemi'],
    ),
  },
  {
    baslik: 'Pediatrik fizyoterapist',
    kurum: 'Lara Çocuk Gelişim Merkezi',
    sehir: 'antalya',
    ilce: 'Muratpaşa',
    calismaSekli: 'tam-zamanli',
    bitisGun: 17,
    iletisim: { eposta: 'ik@ornek-lara-cocuk.test' },
    aciklama: aciklama(
      'Serebral palsi ve gelişim geriliği olan çocuklarla çalışacak fizyoterapist arıyoruz.',
      ['Pediatrik rehabilitasyon deneyimi', 'Çocuklarla iletişimi güçlü', 'NDT eğitimi tercih sebebi'],
      ['Özel sağlık sigortası', 'Süpervizyon desteği'],
    ),
  },
  {
    baslik: 'Evde fizyoterapi hizmeti için serbest fizyoterapist',
    kurum: 'Evde Bakım Ağı',
    sehir: 'kocaeli',
    ilce: 'İzmit',
    calismaSekli: 'serbest',
    bitisGun: 9,
    iletisim: { telefon: '0262 000 00 03', eposta: 'destek@ornek-evde-bakim.test' },
    aciklama: aciklama(
      'Yaşlı ve yatağa bağımlı hastalara ev ziyaretleriyle hizmet verecek fizyoterapistler arıyoruz.',
      ['Ehliyet ve araç', 'Geriatrik hastalarla deneyim'],
      ['Ziyaret başı ücret', 'Kendi programınızı belirleme'],
    ),
  },
  {
    baslik: 'Stajyer fizyoterapist (son sınıf öğrencileri)',
    kurum: 'Selçuklu Fizik Tedavi Merkezi',
    sehir: 'konya',
    ilce: 'Selçuklu',
    calismaSekli: 'staj',
    bitisGun: 40,
    iletisim: { eposta: 'staj@ornek-selcuklu-ftr.test' },
    aciklama: aciklama(
      'Yaz dönemi için son sınıf fizyoterapi öğrencilerine staj imkânı sunuyoruz.',
      ['Fizyoterapi bölümü son sınıf öğrencisi', 'En az 6 hafta devam'],
      ['Deneyimli ekiple birebir çalışma', 'Staj belgesi'],
    ),
  },
  {
    baslik: 'Klinik pilates eğitmeni fizyoterapist',
    kurum: 'Tepebaşı Denge Stüdyosu',
    sehir: 'eskisehir',
    ilce: 'Tepebaşı',
    calismaSekli: 'yari-zamanli',
    bitisGun: 3,
    iletisim: { telefon: '0222 000 00 04' },
    aciklama: aciklama(
      'Akşam grup derslerimiz için klinik pilates eğitmeni arıyoruz.',
      ['Fizyoterapist unvanı', 'Klinik pilates sertifikası'],
      ['Saatlik ücret', 'Merkezi konum'],
    ),
  },
  {
    baslik: 'Kardiyopulmoner rehabilitasyon fizyoterapisti',
    kurum: 'Seyhan Göğüs Hastalıkları Kliniği',
    sehir: 'adana',
    ilce: 'Seyhan',
    calismaSekli: 'tam-zamanli',
    bitisGun: -4,
    iletisim: { eposta: 'ik@ornek-seyhan-gogus.test' },
    aciklama: aciklama(
      'KOAH ve kalp hastalarının rehabilitasyon programlarında görev alacak fizyoterapist arıyoruz.',
      ['Kardiyopulmoner rehabilitasyon deneyimi'],
      ['Kurumsal çalışma ortamı'],
    ),
  },
  {
    baslik: 'Otel spa merkezi için fizyoterapist (sezonluk)',
    kurum: 'Bodrum Sahil Resort',
    sehir: 'mugla',
    ilce: 'Bodrum',
    calismaSekli: 'tam-zamanli',
    bitisGun: -15,
    iletisim: { eposta: 'kariyer@ornek-bodrum-resort.test' },
    aciklama: aciklama(
      'Mayıs-ekim sezonu için spa merkezimizde çalışacak fizyoterapist arıyoruz.',
      ['İngilizce iletişim', 'Masaj teknikleri bilgisi'],
      ['Konaklama ve yemek', 'Sezon sonu prim'],
    ),
  },
] as const
